@prod_uri = https://gin-restapi.up.railway.app


GET {{prod_uri}}/task

###
GET {{prod_uri}}/tasks/1

###
POST {{prod_uri}}/tasks
Content-Type: application/json

{ 
  "AssingedTo": "Lutfi Ikbal Majid",
  "Task": "Jangan lupa makan nasi yaa",
  "Deadline": "20 Agustus 2022"
}